### Get blogs
GET http://localhost:3001/api/blogs HTTP/1.1

### Add blog
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Blog",
    "author": "Username",
    "url": "blogger.com",
    "likes": 10
}

### Delete a blog
DELETE http://localhost:3001/api/blogs/10 HTTP/1.1

### Update likes of a blog
PUT http://localhost:3001/api/blogs/3 HTTP/1.1
content-type: application/json

{
    "likes": 0
}

### Get users
GET http://localhost:3001/api/users HTTP/1.1

### Create a user
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "username03",
    "name": "name03"
}

### Change username
PUT http://localhost:3001/api/users/username01 HTTP/1.1
content-type: application/json

{
    "username": "username00"
}