### Get blogs
GET http://localhost:3001/api/blogs HTTP/1.1

### Add blog
POST http://localhost:3001/api/blogs/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMDFAZW1haWwuY29tIiwiaWQiOjEsImlhdCI6MTY0NTczNDQxOX0.HSduh6niwsn77326gpWm4RHI2oKYc-uJ8ZyJYXyvbP0
content-type: application/json

{
    "title": "Blog",
    "author": "Username",
    "url": "blogger.com",
    "likes": 10
}

### Delete a blog
DELETE http://localhost:3001/api/blogs/10 HTTP/1.1

### Update likes of a blog
PUT http://localhost:3001/api/blogs/3 HTTP/1.1
content-type: application/json

{
    "likes": 0
}

### Get users
GET http://localhost:3001/api/users HTTP/1.1

### Create a user
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "username04",
    "name": "name04"
}

### Change username
PUT http://localhost:3001/api/users/username00 HTTP/1.1
content-type: application/json

{
    "username": "username01@email.com"
}

### Login as username01@emai.com
POST http://localhost:3001/api/login/ HTTP/1.1
content-type: application/json

{
    "username": "username01@email.com",
    "password": "secret"
}