### Get blogs
GET http://localhost:3001/api/blogs HTTP/1.1

### Add blog
POST http://localhost:3001/api/blogs/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMDFAZW1haWwuY29tIiwiaWQiOjEsImlhdCI6MTY0NTczNDQxOX0.HSduh6niwsn77326gpWm4RHI2oKYc-uJ8ZyJYXyvbP0
content-type: application/json

{
    "title": "Blog",
    "author": "react",
    "url": "blogger.com",
    "likes": 11
}

### Delete a blog
DELETE http://localhost:3001/api/blogs/3 HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMDFAZW1haWwuY29tIiwiaWQiOjEsImlhdCI6MTY0NTczNDQxOX0.HSduh6niwsn77326gpWm4RHI2oKYc-uJ8ZyJYXyvbP0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMDJAZW1haWwuY29tIiwiaWQiOjMsImlhdCI6MTY0NTczNjA0M30.VoeoPNYpj51sdgTj1pxYG8SHD_hpMHkdSDKD3c81zgo

### Update likes of a blog
PUT http://localhost:3001/api/blogs/3 HTTP/1.1
content-type: application/json

{
    "likes": 40
}

### Get users
GET http://localhost:3001/api/users HTTP/1.1

### Create a user
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "username01@email.com",
    "name": "name01"
}

### Change username
PUT http://localhost:3001/api/users/username02 HTTP/1.1
content-type: application/json

{
    "username": "username02@email.com"
}

### Login
POST http://localhost:3001/api/login/ HTTP/1.1
content-type: application/json

{
    "username": "username02@email.com",
    "password": "secret"
}

### Search for blog with react
GET http://localhost:3001/api/blogs?search=ReACT HTTP/1.1

### Get list of authors
GET http://localhost:3001/api/authors HTTP/1.1